FROM node:10.17.0-alpine as build

# ARG URL
# ENV REACT_APP_DJANGO_BACKEND_HOST=$URL
# ENV INLINE_RUNTIME_CHUNK=false

WORKDIR /app
COPY . ./
RUN yarn
RUN yarn build

FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx-default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
